Changed yaml files

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,16 +1,6 @@
 name: ci
 
-on:
-  push:
-    branches:
-      - "*"  # run for branches
-    tags:
-      - "*"  # run for tags
-  pull_request:
-    branches:
-      - "*"  # run for branches
-    tags:
-      - "*"  # run for tags
+on: [push]
 
 jobs:
   test:
@@ -20,13 +10,28 @@ jobs:
       COMMIT: ${{ github.sha }}
       REPO: orders
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/orders/orders/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
       - uses: actions/checkout@v2
 
+      - run: touch starting_test_SetupJDK18_25
+      - run: rm starting_test_SetupJDK18_25
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
 
+      - run: touch starting_test_CacheMavenpackages_30
+      - run: rm starting_test_CacheMavenpackages_30
       - name: Cache Maven packages
         uses: actions/cache@v2
         with:
@@ -34,16 +39,24 @@ jobs:
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
 
+      - run: touch starting_test_BuildwithMaven_37
+      - run: rm starting_test_BuildwithMaven_37
       - name: Build with Maven
         run: mvn -B -DskipTests package --file pom.xml
 
+      - run: touch starting_test_UnitTests_40
+      - run: rm starting_test_UnitTests_40
       - name: Unit Tests
         run: mvn -q test
 
+      - run: touch starting_test_IntegrationTests_43
+      - run: rm starting_test_IntegrationTests_43
       - name: Integration Tests
         run: mvn integration-test
 
       # Build docker image for service
+      - run: touch starting_test_Builddockerimage_47
+      - run: rm starting_test_Builddockerimage_47
       - name: Build docker image
         uses: docker/build-push-action@v1
         with:
@@ -55,6 +68,8 @@ jobs:
           tags: ${{ github.sha }}
 
       # Build docker image for mock service
+      - run: touch starting_test_Buildmockdockerimage_58
+      - run: rm starting_test_Buildmockdockerimage_58
       - name: Build mock docker image
         uses: docker/build-push-action@v1
         with:
@@ -65,21 +80,26 @@ jobs:
           tags: latest
           
       # Run simple test against built container
+      - run: touch starting_test_Testdockerimage_68
+      - run: rm starting_test_Testdockerimage_68
       - name: Test docker image
         env:
           DOCKER_BUILDKIT: 1
         run: ./test/test.sh container.py --tag ${GITHUB_SHA}
 
       # Upload coverage results to coveralls
+      - run: touch starting_test_SubmitCoveralls_74
+      - run: rm starting_test_SubmitCoveralls_74
       - name: Submit Coveralls
         env:
           COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
         run: mvn -DrepoToken=${COVERALLS_TOKEN} -DserviceJobId=${GITHUB_RUN_ID} -Dbranch=${GITHUB_REF} -DpullRequest=${GITHUB_HEAD_REF} -DserviceName=GITHUB verify jacoco:report coveralls:report
 
       # Push to dockerhub
+      - run: touch starting_test_PushtoDockerHub_80
+      - run: rm starting_test_PushtoDockerHub_80
       - name: Push to Docker Hub
         uses: docker/build-push-action@v1
-        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
         with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
@@ -87,3 +107,34 @@ jobs:
           repository: ${{ env.GROUP }}/${{ env.REPO }}
           tag_with_ref: true
           tag_with_sha: true
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          python .github/workflows/script.py
+      - name: Pushes analysis to another repository
+        if: always()
+        id: push_directory
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+        with:
+          source-directory: 'optimizing-ci-builds-ci-analysis'
+          destination-github-username: 'UT-SE-Research'
+          destination-repository-name: 'ci-analyzes'
+          target-branch: '1676606676-d8dc3b1'
+          target-directory: 'orders/.github/workflows/main.yaml/test'
+        continue-on-error: true
+      - name: Check push directory exit code
+        if: steps.push_directory.outcome == 'failure'
+        run: |
+          echo 'push failed, trying pull and then push'
+          git stash
+          git pull
+          git stash apply
+          while ! git push origin {time}; do
+            git push
+          done
